<?php

namespace AppBundle\Repository;

/**
 * NavigationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavigationRepository extends \Doctrine\ORM\EntityRepository
{
}