##########################################################
##########################################################
######################### VIEWS ##########################
##########################################################
##########################################################

app:
    resource: '@AppBundle/Controller/'
    type: annotation

##########################################################
##########################################################
######################### CRUD ###########################
##########################################################
##########################################################

app_navigation:
    resource: "@AppBundle/Resources/config/routing/navigation.yml"
    prefix:   /navigation
