##########################################################
##########################################################
######################### VIEWS ##########################
##########################################################
##########################################################

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    methods:  [GET, POST]


##########################################################
##########################################################
#################### Admin Panel #########################
##########################################################
##########################################################

admin_panel:
    path:     /admin
    defaults: { _controller: "AppBundle:Default:panel" }

app_navigation:
    resource: "@AppBundle/Resources/config/routing/navigation.yml"
    prefix:   /admin/navigation