##########################################################
##########################################################
######################### VIEWS ##########################
##########################################################
##########################################################

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    methods:  [GET, POST]

app_actuality:
    path:     /actualite
    defaults: { _controller: "AppBundle:Default:actuality" }

app_actuality_season:
    path:     /actualite/cette_saison
    defaults: { _controller: "AppBundle:Default:season" }

app_actuality_ncreation:
    path:     /actualite/nouvelles_creations
    defaults: { _controller: "AppBundle:Default:nCreation" }

app_actuality_pcreation:
    path:     /actualite/precedentes_creations
    defaults: { _controller: "AppBundle:Default:pCeation" }

app_actuality_exotic:
    path:     /actualite/exotiques
    defaults: { _controller: "AppBundle:Default:exotic" }

app_actuality_inspiration:
    path:     /actualite/inspiration
    defaults: { _controller: "AppBundle:Default:inspiration" }

app_actuality_leatherwork:
    path:     /actualite/peausseries
    defaults: { _controller: "AppBundle:Default:leatherwork" }

#----------------------------------------------------------------------
#                   TAILORED
#----------------------------------------------------------------------

app_tailored:
    path:     /sur_mesure
    defaults: { _controller: "AppBundle:Tailored:tailored" }

app_tailored_galery:
    path:     /sur_mesure/galerie
    defaults: { _controller: "AppBundle:Tailored:tailoreGalery" }

#----------------------------------------------------------------------
#                   MANUFACTURING
#----------------------------------------------------------------------

app_line_galery:
    path:     /ligne_bottier/galerie
    defaults: { _controller: "AppBundle:line:lineGalery" }

#----------------------------------------------------------------------
#                   MANUFACTURING
#----------------------------------------------------------------------

app_manufacturing:
    path:     /fabrication
    defaults: { _controller: "AppBundle:manufacturing:manufacturing" }

app_manufacturing_galery:
    path:     /fabrication/galerie
    defaults: { _controller: "AppBundle:manufacturing:manufacturingGalery" }

#----------------------------------------------------------------------
#                   LEFT OVER
#----------------------------------------------------------------------

app_left_over:
    path:     /laisses_pour_compte
    defaults: { _controller: "AppBundle:LeftOver:leftOver" }

app_left_over_galery_escaprin:
    path:     /laisses_pour_compte/escarpin
    defaults: { _controller: "AppBundle:LeftOver:leftOverGalery1" }

app_left_over_galery_richelieu:
    path:     /laisses_pour_compte/richelieu
    defaults: { _controller: "AppBundle:LeftOver:leftOverGalery2" }

app_left_over_galery_chukka:
    path:     /laisses_pour_compte/chukka
    defaults: { _controller: "AppBundle:LeftOver:leftOverGalery3" }

#----------------------------------------------------------------------
#                   CONTACT
#----------------------------------------------------------------------

app_contact:
    path:     /contact
    defaults: { _controller: "AppBundle:contact:contact" }

#----------------------------------------------------------------------
#                   Legal Notice
#----------------------------------------------------------------------

app_legal_notice:
    path:     /mention
    defaults: { _controller: "AppBundle:contact:notice" }

##########################################################
##########################################################
#################### Admin Panel #########################
##########################################################
##########################################################

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

login:
    path: /login

logout:
    path: /logout

#admin_panel:
#    path:     /admin
#    defaults: { _controller: "AppBundle:Default:panel" }

#app_navigation:
#    resource: "@AppBundle/Resources/config/routing/navigation.yml"
#    prefix:   /admin/navigation

#----------------------------------------------------------------------
#                   MEDIA
#----------------------------------------------------------------------

media_index:
    path:     /admin
    defaults: { _controller: "AppBundle:Media:index" }
    methods:  GET

media_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Media:show" }
    methods:  GET

media_new:
    path:     /new
    defaults: { _controller: "AppBundle:Media:new" }
    methods:  [GET, POST]

media_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Media:edit" }
    methods:  [GET, POST]

media_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Media:delete" }
    methods:  DELETE