navigation_index:
    path:     /
    defaults: { _controller: "AppBundle:Navigation:index" }
    methods:  GET

navigation_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Navigation:show" }
    methods:  GET

navigation_new:
    path:     /new
    defaults: { _controller: "AppBundle:Navigation:new" }
    methods:  [GET, POST]

navigation_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Navigation:edit" }
    methods:  [GET, POST]

navigation_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Navigation:delete" }
    methods:  DELETE
